/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "import-spec-parent"
include(":apache-beam-example")
include(":import-spec")
include(":neo4j-admin-example")
include(":import-spec-examples-parent")
project(":apache-beam-example").projectDir = file("examples/apache-beam")
project(":import-spec").projectDir = file("core")
project(":neo4j-admin-example").projectDir = file("examples/neo4j-admin")
project(":import-spec-examples-parent").projectDir = file("examples")
