#!/usr/bin/env sh

$(git rev-parse --show-toplevel)/mvnw sortpom:sort spotless:apply -f .teamcity
$(git rev-parse --show-toplevel)/mvnw sortpom:sort spotless:apply -DspotlessFiles=src/main/java/.*.java

git update-index --again
