/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    testImplementation(project(":import-spec"))
    testImplementation(libs.org.apache.beam.beam.sdks.java.myextensions.sql)
    testImplementation(libs.org.apache.beam.beam.sdks.java.io.parquet)
    testImplementation(libs.org.apache.hadoop.hadoop.client.runtime)
    testImplementation(libs.org.apache.hadoop.hadoop.common)
    testImplementation(libs.org.apache.hadoop.hadoop.mapreduce.client.core)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.vintage.junit.vintage.engine)
    testImplementation(libs.org.neo4j.neo4j.cypher.dsl)
    testImplementation(libs.org.neo4j.driver.neo4j.java.driver)
    testImplementation(libs.org.slf4j.slf4j.nop)
    testImplementation(libs.org.testcontainers.junit.jupiter)
    testImplementation(libs.org.testcontainers.neo4j)
    testImplementation(libs.org.testcontainers.testcontainers)
}

description = "apache-beam-example"

java {
    withJavadocJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
